pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Build docker and install jar'
            }
        }
        stage('Test') {
            steps {
                echo 'Test app'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy to prod'
            }
        }
    }
} 